### ISSUE TITLE
Freepik (and other marketplaces)

### ISSUE THREAD

**Issue by daliovic** [episage/next-page-chrome-extension#4]
Hi Episage
Thank you so much for this extension
I was trying to make it work on marketplaces such as Freepik / Envato Elements... but I don't seem to know how. These are my rules for FreePik:

url ^https://www\.freepik\.com/search
pageElement //figure[@class="showcase__item"]
nextLink //a[@class="pagination__next"]

Logically it should be working just fine but for some reason it's not. 
Also, I wanted to know if there is a tool that allows me to live test the xPath rules. In the help page, the shortcut for what you said LPT is messed (âŒ˜+F).
Any help will be much appreciated. Thank you again

**Comment by episage** [comment]
Hi,

```
url ^https://www\.freepik\.com/search
pageElement //figure[@Class="showcase__item"]
nextLink //a[@Class="pagination__next"]

```

 - you forgot to escape forward slash in `/search`
 - rule for `nextLink` doesn't work, you need to try something better, I found `//a[contains(concat(' ',normalize-space(@class),' '),' pagination__next ')]` to work well
 - `Class` should be lowercase

```
url ^https://www\.freepik\.com\/search
pageElement //figure[@class="showcase__item"]
nextLink //a[contains(concat(' ',normalize-space(@class),' '),' pagination__next ')]
rule for www.freepik.com
```
The above works but since the website uses JS to load images NextPage is not yet capable of loading them :( 
I think it's the next most wanted feature

**Comment by daliovic** [comment]
Thank you so much for your reply Tomasz. I really appreciate that.
